### PR TITLE
Updated section about ciphers without integrity protection

### PR DESCRIPTION
**Pull request by hannestschofenig**

### CODE REVIEW

**Review by russhousley — CHANGES_REQUESTED** [review]
This part:

At the next boot, the bootloader will recognize a new firmware image in the 
secondary slot and will start decrypting the downloaded image sector-by-sector
and will swap it with the image found in the primary slot. 

The swap should only take place after the signature on the plaintext is verified.

**Comment by hannestschofenig** [comment]
Thanks for your comment, Russ.

Here is the issue: Only after the swap has been completed the plaintext firmware image is in the primary slot. Before the swap, the encrypted firmware image was in the secondary slot.

It would be possible to do a "dummy decrypt" to compute the hash prior to doing the decrypt with swapping.

**Comment by russhousley** [comment]
Yes, the AES-CTR and AES-CBC document in the COSE WG states that the signature provides the integrity protection, so this description needs to say how that happens.

**Comment by hannestschofenig** [comment]
Russ, I have added text to address your comment.

**Pull request merged**
