### PR TITLE
fix: moved extensions into SUIT_Parameters

### LINKED ISSUE #7: [hackathon114] SUIT_Encryption_Info may not be associated with a specific firmware image
SUIT_Encryption_Info was defined in the past SUIT Manifest core document
describing how to decrypt the firmware image,
but in this document it may not be associated with any component.

I will create a Pull Request to move SUIT_Encryption_Info under the suit-manifest.

# In the past SUIT Manifest v14 draft
[draft-ietf-suit-manifest-14](https://datatracker.ietf.org/doc/html/draft-ietf-suit-manifest-14)

```
SUIT_Envelope = {
  suit-manifest: <<{
    suit-common: <<{
      suit-components: [
        [ h'0A' ],
        [ h'0B' ]
      ]
    }>>,
    suit-install: <<{
      suit-directive-set-component-index: 0 / for Component [ h'0A' ] /,
      suit-directive-override-parameters: {
        suit-parameters-encryption-info: SUIT_Encryption_Info / of [ h'0A' ] /
      },
      suit-directive-set-component-index: 1 / for Component [ h'0B' ] /,
      suit-directive-override-parameters: {
        suit-parameters-encryption-info: SUIT_Encryption_Info / of [ h'0B' ] /
      }
    }>>
  }>>
}
```

# In the Firmware Encryption draft
```
SUIT_Envelope = {
  suit-manifest: <<{
    suit-common: <<{
      suit-components: [
        [ h'0A' ],
        [ h'0B' ]
      ]
    }>>,
    suit-install: <<{
      suit-directive-set-component-index: 0 / for Component [ h'0A' ] /,
      / do something using SUIT_Encryption_Info below? /,
      suit-directive-set-component-index: 1 / for Component [ h'0B' ] /,
      / do something using SUIT_Encryption_Info below? /
    }>>
  }>>,
  suit-protection-wrappers: <<{
    *(int/str) => [
      SUIT_Encryption_Info / for Component [ h'0A' ] ? /,
      SUIT_Encryption_Info / for component [ h'0B' ] ? /
    ]
  }>>
}
```

### PR DESCRIPTION
**Pull request by kentakayama**
Fixes #7 moving `SUIT_Encryption_Info` into `suit-directive-(set|override)-parameters` .

### CODE REVIEW

**Comment by hannestschofenig** [comment]
Ken, here is the reasoning for moving encryption functionality outside the SUIT manifest: When the firmware author needs to encrypt a payload for a specific recipient it needs to know its public key (for HPKE) or its symmetric key (for AES-KW). Since the firmware author does not typically know the recipients ahead of time, it cannot perform this encryption operation. What he can, however, do is to digitally sign the manifest (and thereby the firmware image) since it only requires its private key.

Later the distribution system, before delivering the firmware to the devices, will encrypt the firmware images. It cannot modify the manifest anymore since otherwise the signature previously generated would be invalidated. Hence, any information regarding firmware encryption has to go into the envelope.

I hope this makes sense.

For this reason, I believe the current text in the document is correct.

**Comment by kentakayama** [comment]
I've misunderstood your intention. Are these correct?

- Author has the raw firmware image and creates `SUIT_Envelope` by signing the `SUIT_Manifest` with its signing key.
- Distribution System receives the raw firmware image and its `SUIT_Envelope` from the Author, then encrypts the firmware. It appends `SUIT_Encryption_Info` to `SUIT_Envelope` (outside the `SUIT_Manifest`).
- Device verifies the `SUIT_Manifest` and decrypts encrypted firmware image using `SUIT_Encryption_Info`.

My concern is that the `SUIT_Encryption_Info` would be untrusted because it locates outside the signature.

How about this one?
- The order of suit-protection-wrappers array corresponds to the suit-components array in suit-common
  - it can be `null` if no decryption is required
- The Device can verify whether the decrypted firmware image is correct using the digest hash of raw firmware image
  - the image digest and the image size are trusted because they are inside the `SUIT_Manifest`
  - though the `SUIT_Encryption_Info`s are untrusted because they are outside the `SUIT_Manifest`
- The Author MUST aware that the firmware will be encrypted by Distribution System
  - to create appropriate suit-install section

```
/ SUIT_Envelope = / {
  suit-authentication-wrapper: SUIT_Authentication,

  / inside the signature /
  suit-manifest : << {
    suit-common: << {
      suit-components: [
        [h'00'] / to be decrypted firmware /,
        [h'01'] / encrypted firmware /
      ]
    } >>,
    suit-install: << [
      / loads encrypted firmware /
      suit-directive-set-component-index 1 / [h'01'] /,
      suit-directive-override-parameters {
        suit-parameter-uri: "#encrypted-firmware" / integrated payload to be added /
      },
      suit-directive-fetch,

      / decrypts it /
      suit-directive-set-component-index 0 / [h'00'] /,
      suit-directive-override-parameters {
        suit-parameter-source-component: 1 / [h'01'] /
      },
      suit-directive-decrypt / new directive to decrypt the component [h'01'] using SUIT_Encryption_Info /,

      / verify decrypted firmware /
      suit-directive-override-parameters {
        suit-parameter-image-digest: <<the digest of raw firmware image [h'00']>>,
        suit-parameter-image-size: <<the size of raw firmware image [h'00']>>
      },
      suit-condition-image-match
    ] >>
  } >>,

  / outside the signature and added by Distribution System/
  suit-protection-wrappers : << [
    SUIT_Encryption_Info / for [h'00'] /
  ] >>,
  "#encrypted-firmware": h'beef'
}
```

**Comment by hannestschofenig** [comment]
> My concern is that the SUIT_Encryption_Info would be untrusted because it locates outside the signature.

The distribution system is not untrusted but rather trusted to do the encryption of the plaintext firmware image and to distribute it to the intended recipients. 

If the author already knows the recipients ahead of time and has their public keys, then it can also encrypt the firmware image without relying on the distribution system. 

Hence, I do not believe that the wording that the distribution system is untrusted is correct. Note that the recipient will get to learn that the encryption has been applied by the distribution system since the encryption info is also signed. 

The recipient (device) can still check the signature of the manifest to verify whether the plaintext image has been unchanged.

Hence, I don't see a problem with the approach

**Comment by hannestschofenig** [comment]
Btw, I agree with you that the manifest needs to carry a hash of the plaintext firmware and it also needs to contain instructions for matching the hash against a specific value.

The reason why I believe that no commands for processing the encrypted payload are needed is simply because the encryption must happen before any of the other processing steps need to take place. Otherwise nothing can proceed. Is this the right approach? I don't know.

**Comment by hannestschofenig** [comment]
I wonder whether we should bring this up on the SUIT mailing list since it is an important design decision.

**Comment by kentakayama** [comment]
The term "untrusted" I used was ambiguous, but I meant the part `SUIT_Encryption_Info` was outside the signature.

Before discussing in the mailing list let me confirm this:

Distribution System is trusted
- case A-1) as a firmware server and a device management infrastructure
- case A-2) as a firmware server and a device management infrastructure, and also **a manifest signer**

The firmware is encrypted by
- case B-1) the Author
- case B-2) the Distribution System

With case A-2, the Distribution System can just update the manifest and then update the signature because Devices trusts its public key.
With case B-1, the Author can create encrypted firmware and its manifest, so that there is no need Distribution System to modify the manifest.
They work well with current SUIT Manifest, but our case `(A-1, B-2)` does not especially with non-integrated payload.

Am I correct?

**Comment by hannestschofenig** [comment]
>  They work well with current SUIT Manifest, but our case (A-1, B-2) does not especially with non-integrated payload.

I think you are saying that because a non-integrated payload requires a URI to be included in the manifest, which will then be integrity protected. Hence, the distribution system will not be able to change that URL and it will typically not have permissions to replace the content of the referenced file. Is this correct?

FYI: I think it would be good to have examples of all these cases in the draft.

**Comment by hannestschofenig** [comment]
Here is what Øyvind proposes in https://mailarchive.ietf.org/arch/msg/suit/9ZeqNixEZ8HhTTxkXypTQmmfLOM/

> My suggestion is for something like this (which I think is very similar to what Ken mentions): SUIT-protection-wrappers is a list of SUIT_Encryption_Info elements, and these are referenced by index in the manifest, e.g. by having a uint decryption-info parameter (tied to a specific component), which, when present, instructs the manifest processor to decrypt during a subsequent fetch or copy to that component. There can also be a corresponding encryption-info parameter for performing encryption in the same manner.

**Pull request merged**
